package Demo;
import DAO.DBAccess;
import Entities.Category;
import Entities.Student;
import Entities.Teacher;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
/**
 *
 * @author priyammodi
 */
public class AddVaccineDetailsJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private String dateFormat = "MM-dd-yyyy";
    /**
     * Creates new form AddVaccineDetailsJPanel
     */
    public AddVaccineDetailsJPanel(JPanel userProcessContainer) {
        this.userProcessContainer = userProcessContainer;
        initComponents();
        BindStudents();
        System.out.println("Printing Initail Value");
        System.out.println(HIB_Dose1.getText());
    }

    public void BindStudents(){
        try{
           DBAccess db = new DBAccess();
           drpdwnStudent.removeAllItems();
           
            for(Student student : db.fetchStudents()){
                drpdwnStudent.addItem(student);
            }
       }
       catch(Exception e){
           System.out.println(e);
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        drpdwnStudent = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        subVaccine = new javax.swing.JButton();
        HIB_Dose1 = new javax.swing.JTextField();
        DTap_Dose1 = new javax.swing.JTextField();
        DTap_Dose2 = new javax.swing.JTextField();
        DTap_Dose3 = new javax.swing.JTextField();
        DTap_Dose4 = new javax.swing.JTextField();
        Polio_Dose1 = new javax.swing.JTextField();
        Hepatitis_Dose1 = new javax.swing.JTextField();
        Polio_Dose2 = new javax.swing.JTextField();
        Polio_Dose3 = new javax.swing.JTextField();
        MMR_Dose1 = new javax.swing.JTextField();
        Hepatitis_Dose3 = new javax.swing.JTextField();
        Hepatitis_Dose2 = new javax.swing.JTextField();
        Varicella_Dose1 = new javax.swing.JTextField();

        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Add Student Vaccination Details");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("Select Student");

        drpdwnStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drpdwnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpdwnStudentActionPerformed(evt);
            }
        });

        jLabel3.setText("HIB");

        jLabel4.setText("DTap");

        jLabel5.setText("POLIO");

        jLabel6.setText("MMR");

        jLabel8.setText("Hepatitis B");

        jLabel10.setText("Dose 1");

        jLabel11.setText("Dose - 1");

        jLabel12.setText("Dose -1");

        jLabel13.setText("Dose - 3");

        jLabel17.setText("Dose - 2");

        jLabel18.setText("Dose - 3");

        jLabel19.setText("Dose - 4");

        jLabel20.setText("Dose - 2");

        jLabel21.setText("Dose - 1");

        jLabel22.setText("Dose - 1");

        jLabel23.setText("Dose - 2");

        jLabel24.setText("Dose - 3");

        jLabel25.setText("Varicella");

        jLabel26.setText("Dose - 1");

        subVaccine.setText("SUBMIT");
        subVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subVaccineActionPerformed(evt);
            }
        });

        HIB_Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIB_Dose1ActionPerformed(evt);
            }
        });

        DTap_Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTap_Dose1ActionPerformed(evt);
            }
        });

        DTap_Dose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTap_Dose3ActionPerformed(evt);
            }
        });

        DTap_Dose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTap_Dose4ActionPerformed(evt);
            }
        });

        Polio_Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Polio_Dose1ActionPerformed(evt);
            }
        });

        Polio_Dose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Polio_Dose2ActionPerformed(evt);
            }
        });

        Polio_Dose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Polio_Dose3ActionPerformed(evt);
            }
        });

        MMR_Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMR_Dose1ActionPerformed(evt);
            }
        });

        Hepatitis_Dose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hepatitis_Dose3ActionPerformed(evt);
            }
        });

        Hepatitis_Dose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hepatitis_Dose2ActionPerformed(evt);
            }
        });

        Varicella_Dose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(185, 185, 185)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(drpdwnStudent, 0, 245, Short.MAX_VALUE)
                            .addComponent(HIB_Dose1)
                            .addComponent(DTap_Dose1)
                            .addComponent(DTap_Dose2)
                            .addComponent(DTap_Dose3)
                            .addComponent(DTap_Dose4)
                            .addComponent(Polio_Dose1)
                            .addComponent(Polio_Dose2)
                            .addComponent(Polio_Dose3)
                            .addComponent(MMR_Dose1)
                            .addComponent(Hepatitis_Dose1)
                            .addComponent(Hepatitis_Dose2)
                            .addComponent(Hepatitis_Dose3)
                            .addComponent(Varicella_Dose1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(subVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drpdwnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(HIB_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(DTap_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DTap_Dose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DTap_Dose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DTap_Dose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Polio_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Polio_Dose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Polio_Dose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MMR_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hepatitis_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hepatitis_Dose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hepatitis_Dose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Varicella_Dose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subVaccine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
    userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void drpdwnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpdwnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpdwnStudentActionPerformed

    private void HIB_Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIB_Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIB_Dose1ActionPerformed

    private void Polio_Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Polio_Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Polio_Dose1ActionPerformed

    private void DTap_Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTap_Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTap_Dose1ActionPerformed

    private void MMR_Dose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMR_Dose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMR_Dose1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void subVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subVaccineActionPerformed
        // TODO add your handling code here:
        try{
        Student objStudent = new Student();
        Student objname = (Student)drpdwnStudent.getSelectedItem();
        Date dateofHIB_Dose1 = new SimpleDateFormat(dateFormat).parse(HIB_Dose1.getText());
        Date dateofDTap_Dose1 = new SimpleDateFormat(dateFormat).parse(DTap_Dose1.getText());
        Date dateofDTap_Dose2 = new SimpleDateFormat(dateFormat).parse(DTap_Dose2.getText());
        Date dateofDTap_Dose3 = new SimpleDateFormat(dateFormat).parse(DTap_Dose3.getText());
        Date dateofDTap_Dose4 = new SimpleDateFormat(dateFormat).parse(DTap_Dose4.getText());
        Date dateofPolio_Dose1 = new SimpleDateFormat(dateFormat).parse(Polio_Dose1.getText());
        Date dateofPolio_Dose2 = new SimpleDateFormat(dateFormat).parse(Polio_Dose2.getText());
        Date dateofPolio_Dose3 = new SimpleDateFormat(dateFormat).parse(Polio_Dose3.getText());
        Date dateofMMR_Dose1 = new SimpleDateFormat(dateFormat).parse(MMR_Dose1.getText());
        Date dateofHepatitis_Dose1 = new SimpleDateFormat(dateFormat).parse(Hepatitis_Dose1.getText());
        Date dateofHepatitis_Dose2 = new SimpleDateFormat(dateFormat).parse(Hepatitis_Dose2.getText());
        Date dateofHepatitis_Dose3 = new SimpleDateFormat(dateFormat).parse(Hepatitis_Dose3.getText());
        Date dateofVariclla_Dose1 = new SimpleDateFormat(dateFormat).parse(Varicella_Dose1.getText());
        objStudent.setStudentId(objname.getStudentId());
        objStudent.setHIB_Dose1(dateofHIB_Dose1);
        objStudent.setDTap_Dose1(dateofDTap_Dose1);
        objStudent.setDTap_Dose2(dateofDTap_Dose2);
        objStudent.setDTap_Dose3(dateofDTap_Dose3);
        objStudent.setDTap_Dose4(dateofDTap_Dose4);
        objStudent.setPolio_Dose1(dateofPolio_Dose1);
        objStudent.setPolio_Dose2(dateofPolio_Dose2);
        objStudent.setPolio_Dose3(dateofPolio_Dose3);
        objStudent.setMMR_Dose1(dateofMMR_Dose1);
        objStudent.setHepatitis_Dose1(dateofHepatitis_Dose1);
        objStudent.setHepatitis_Dose2(dateofHepatitis_Dose2);
        objStudent.setHepatitis_Dose3(dateofHepatitis_Dose3);
        objStudent.setVaricella_Dose1(dateofVariclla_Dose1);
        System.out.println("Printing Student ---");
        System.out.println("" + objStudent.getHIB_Dose1());
        //Adding student data to Database
        DBAccess db = new DBAccess();
        db.addVaacine(objStudent);
        
        // Navigate to student option screen with confirmation msg
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        StudnetJPanel student = new StudnetJPanel(userProcessContainer, "Student Vaccine Details added successfully !!");
        userProcessContainer.add("Student", student);
        layout.next(userProcessContainer);
        
       }
       catch(Exception e){
           System.out.println(e);
       }                           
    }//GEN-LAST:event_subVaccineActionPerformed

    private void Hepatitis_Dose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hepatitis_Dose3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hepatitis_Dose3ActionPerformed

    private void Hepatitis_Dose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hepatitis_Dose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hepatitis_Dose2ActionPerformed

    private void Polio_Dose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Polio_Dose3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Polio_Dose3ActionPerformed

    private void Polio_Dose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Polio_Dose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Polio_Dose2ActionPerformed

    private void DTap_Dose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTap_Dose4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTap_Dose4ActionPerformed

    private void DTap_Dose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTap_Dose3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTap_Dose3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DTap_Dose1;
    private javax.swing.JTextField DTap_Dose2;
    private javax.swing.JTextField DTap_Dose3;
    private javax.swing.JTextField DTap_Dose4;
    private javax.swing.JTextField HIB_Dose1;
    private javax.swing.JTextField Hepatitis_Dose1;
    private javax.swing.JTextField Hepatitis_Dose2;
    private javax.swing.JTextField Hepatitis_Dose3;
    private javax.swing.JTextField MMR_Dose1;
    private javax.swing.JTextField Polio_Dose1;
    private javax.swing.JTextField Polio_Dose2;
    private javax.swing.JTextField Polio_Dose3;
    private javax.swing.JTextField Varicella_Dose1;
    private javax.swing.JComboBox drpdwnStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subVaccine;
    // End of variables declaration//GEN-END:variables
}
