/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tejal
 */
public class StudnetJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    /**
     * Creates new form StudnetJPanel
     */
    public StudnetJPanel(JPanel userProcessContainer, String confirmationmsg) {
        this.userProcessContainer = userProcessContainer;
        initComponents();
        
        addConfirmationMsg(confirmationmsg);
    }
    
    // Add confirmation msg after creating student
    public void addConfirmationMsg(String confirmationmsg){
        if(confirmationmsg != null && !confirmationmsg.trim().equals("")){
            lblConfirmation.setText(confirmationmsg);
        }
        else{
            lblConfirmation.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudentCreate = new javax.swing.JButton();
        btnStudentView = new javax.swing.JButton();
        lblConfirmation = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studentJLabel = new javax.swing.JLabel();

        btnStudentCreate.setText("Create");
        btnStudentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCreateActionPerformed(evt);
            }
        });

        btnStudentView.setText("View");
        btnStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewActionPerformed(evt);
            }
        });

        lblConfirmation.setBackground(new java.awt.Color(102, 102, 102));
        lblConfirmation.setFont(new java.awt.Font("Bradley Hand", 1, 24)); // NOI18N
        lblConfirmation.setForeground(new java.awt.Color(0, 153, 0));
        lblConfirmation.setText("Confimation Text");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        studentJLabel.setText(" Student Information and Creation ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(studentJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStudentCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(btnStudentView, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addComponent(lblConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentView, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCreateActionPerformed
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        CreateStudentJPanel createStudent = new CreateStudentJPanel(userProcessContainer);
        userProcessContainer.add("CreateStudent", createStudent);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudentCreateActionPerformed

    private void btnStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewActionPerformed
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        ViewStudentJPanel viewStudent = new ViewStudentJPanel(userProcessContainer);
        userProcessContainer.add("ViewStudent", viewStudent);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudentViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentCreate;
    private javax.swing.JButton btnStudentView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel studentJLabel;
    // End of variables declaration//GEN-END:variables
}
